In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [2]:
arr.shape

(5,)

In [3]:
arr.ndim

1

In [8]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr1.shape

(3, 3)

In [10]:
arr1.ndim

2

In [5]:
arr2 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [6]:
arr2.ndim

3

In [7]:
arr2.shape

(3, 3, 3)

In [12]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr3.shape

(2, 3)

In [14]:
arr.ndim

1

In [18]:
arr4 = np.zeros([3,4])
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
arr5 = np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
arr3.shape

(2, 3)

In [23]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
b =arr3.reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
arr2.size

27

In [26]:
arr2.shape

(3, 3, 3)

In [27]:
arr2.dtype

dtype('int64')

In [29]:
a = arr2.astype(float)
a

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]]])

In [ ]:
ar = np.array([[3,6,1,2],[9,0,4,2]])
ar.sort()
ar


In [39]:
ar.argsort()

array([[2, 3, 0, 1],
       [1, 3, 2, 0]])

In [40]:
ar.sum()

np.int64(27)

In [41]:
ar

array([[3, 6, 1, 2],
       [9, 0, 4, 2]])

In [42]:
ar.sum(axis=0)

array([12,  6,  5,  4])

In [43]:
ar.sum(axis=1)

array([12, 15])

In [44]:
ar.max

<function ndarray.max>

In [45]:
ar.max()

np.int64(9)

In [46]:
ar.min()

np.int64(0)

In [48]:
ar.argmin()

np.int64(5)

In [49]:
ar[1][1]

np.int64(0)

In [50]:
ar

array([[3, 6, 1, 2],
       [9, 0, 4, 2]])

In [54]:
ar[1][2]


np.int64(4)

In [56]:
ar[1,2]

np.int64(4)

In [57]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [61]:
arr2[0][2][1]

np.int64(8)

In [75]:
arr3[1:2]

array([[4, 5, 6]])

In [76]:
arr3[1:3]

array([[4, 5, 6]])

In [80]:
arr.sum()

np.int64(15)

In [81]:
arr.mean()

np.float64(3.0)

In [82]:
arr3.mean()

np.float64(3.5)

In [85]:
arr3.size

6