In [50]:
import pandas as pd
import numpy as np
import seaborn as sns

In [51]:
df = pd.read_csv("heart.csv")

In [52]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [53]:
df.age.min()

np.int64(29)

In [54]:
df.age.max()

np.int64(77)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [56]:
df.cp

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    0
1024    0
Name: cp, Length: 1025, dtype: int64

In [57]:
df.cp.unique()

array([0, 1, 2, 3])

In [58]:
df.trestbps.unique()

array([125, 140, 145, 148, 138, 100, 114, 160, 120, 122, 112, 132, 118,
       128, 124, 106, 104, 135, 130, 136, 180, 129, 150, 178, 146, 117,
       152, 154, 170, 134, 174, 144, 108, 123, 110, 142, 126, 192, 115,
        94, 200, 165, 102, 105, 155, 172, 164, 156, 101])

In [59]:
df.chol.unique()

array([212, 203, 174, 294, 248, 318, 289, 249, 286, 149, 341, 210, 298,
       204, 308, 266, 244, 211, 185, 223, 208, 252, 209, 307, 233, 319,
       256, 327, 169, 131, 269, 196, 231, 213, 271, 263, 229, 360, 258,
       330, 342, 226, 228, 278, 230, 283, 241, 175, 188, 217, 193, 245,
       232, 299, 288, 197, 315, 215, 164, 326, 207, 177, 257, 255, 187,
       201, 220, 268, 267, 236, 303, 282, 126, 309, 186, 275, 281, 206,
       335, 218, 254, 295, 417, 260, 240, 302, 192, 225, 325, 235, 274,
       234, 182, 167, 172, 321, 300, 199, 564, 157, 304, 222, 184, 354,
       160, 247, 239, 246, 409, 293, 180, 250, 221, 200, 227, 243, 311,
       261, 242, 205, 306, 219, 353, 198, 394, 183, 237, 224, 265, 313,
       340, 259, 270, 216, 264, 276, 322, 214, 273, 253, 176, 284, 305,
       168, 407, 290, 277, 262, 195, 166, 178, 141])

In [60]:
df.fbs.unique()

array([0, 1])

In [61]:
df.restecg.unique()

array([1, 0, 2])

In [62]:
df.thalach.max()

np.int64(202)

In [63]:
df.exang.unique()

array([0, 1])

In [64]:
df.oldpeak.unique()

array([1. , 3.1, 2.6, 0. , 1.9, 4.4, 0.8, 3.2, 1.6, 3. , 0.7, 4.2, 1.5,
       2.2, 1.1, 0.3, 0.4, 0.6, 3.4, 2.8, 1.2, 2.9, 3.6, 1.4, 0.2, 2. ,
       5.6, 0.9, 1.8, 6.2, 4. , 2.5, 0.5, 0.1, 2.1, 2.4, 3.8, 2.3, 1.3,
       3.5])

In [65]:
df.slope.unique()

array([2, 0, 1])

In [66]:
df.ca.unique()

array([2, 0, 1, 3, 4])

In [67]:
df.thal.unique()

array([3, 2, 1, 0])

In [68]:
x = df.drop("target",axis=1)

In [69]:
x

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  
0         2   2     3  
1         0   0     3  
2         0   0     3  
3         2   1     3  
4         1   3     2  
...     ...  ..   ...  
1020      2   0     2  
1021      1   1     3  
1022      1   1     2  
1023      2   0     2  
1024      1   1     3  

[1025 rows x 13 columns]

In [70]:
print(df.thalach.max())
print(df.thalach.min())


202
71


In [71]:
y = df["target"]

In [72]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [73]:
y.unique()

array([0, 1])

In [74]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [75]:
x_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
205   42    1   3       148   244    0        0      178      0      0.8   
735   50    1   2       129   196    0        1      163      0      0.0   
85    44    1   1       120   220    0        1      170      0      0.0   
874   59    1   3       160   273    0        0      125      0      0.0   
486   41    1   0       110   172    0        0      158      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
467   47    1   0       110   275    0        0      118      1      1.0   
568   54    0   2       160   201    0        1      163      0      0.0   
13    51    1   0       140   298    0        1      122      1      4.2   
824   61    1   0       138   166    0        0      125      1      3.6   
694   39    1   0       118   219    0        1      140      0      1.2   

     slope  ca  thal  
205      2   2     2  
735      2   0     2  
85       2   0     2  
874      2   0     2  
486      2   0     3  
..     ...  ..   ...  
467      1   1     2  
568      2   1     2  
13       1   3     3  
824      1   1     2  
694      1   0     3  

[820 rows x 13 columns]

In [76]:
y_train

205    1
735    1
85     1
874    0
486    0
      ..
467    0
568    1
13     0
824    0
694    0
Name: target, Length: 820, dtype: int64

In [77]:
x_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
355   46    0   0       138   243    0        0      152      1      0.0   
766   57    1   0       110   335    0        1      143      1      3.0   
604   47    1   2       130   253    0        1      179      0      0.0   
111   53    1   0       142   226    0        0      111      1      0.0   
837   52    1   2       172   199    1        1      162      0      0.5   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
531   65    0   2       155   269    0        1      148      0      0.8   
106   51    1   0       140   299    0        1      173      1      1.6   
420   57    0   0       128   303    0        0      159      0      0.0   
120   54    1   1       108   309    0        1      156      0      0.0   
286   64    0   2       140   313    0        1      133      0      0.2   

     slope  ca  thal  
355      1   0     2  
766      1   1     3  
604      2   0     2  
111      2   0     3  
837      2   0     3  
..     ...  ..   ...  
531      2   0     2  
106      2   0     3  
420      2   1     2  
120      2   0     3  
286      2   0     3  

[205 rows x 13 columns]

In [78]:
y_test

355    1
766    0
604    1
111    1
837    1
      ..
531    1
106    0
420    1
120    1
286    1
Name: target, Length: 205, dtype: int64

In [79]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()

In [80]:
model = dt.fit(x_train,y_train)

In [81]:
model

DecisionTreeClassifier()

In [82]:
y_pred = dt.predict(x_test)
y_pred

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1])

In [83]:
from sklearn.metrics import confusion_matrix,classification_report

In [94]:
accuracy = accuracy_score(y_pred,y_test)
accuracy

1.0

In [85]:
confusion_matrix(y_pred,y_test)

array([[ 97,   0],
       [  0, 108]])

In [86]:
print(classification_report(y_pred,y_test))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        97
           1       1.00      1.00      1.00       108

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205



In [87]:
y_pred

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1])

In [88]:
y_test

355    1
766    0
604    1
111    1
837    1
      ..
531    1
106    0
420    1
120    1
286    1
Name: target, Length: 205, dtype: int64

In [89]:
import pickle

Save the Model

In [90]:
pickle.dump(accuracy,open("acc.pkl","wb"))

In [91]:
pickle.dump(model,open("model1.pkl","wb"))

To Load the Model

In [92]:
#pickle.load(open("model1.pkl","rb"))

In [93]:
pickle.load(open("acc.pkl","rb"))

1.0