In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Training.csv")

In [3]:
df

itching  nodal_skin_eruptions  chills  joint_pain  stomach_pain  \
0           1                     1       0           0             0   
1           0                     1       0           0             0   
2           1                     1       0           0             0   
3           1                     0       0           0             0   
4           1                     1       0           0             0   
...       ...                   ...     ...         ...           ...   
4915        0                     0       0           0             0   
4916        0                     0       0           0             0   
4917        0                     0       0           0             0   
4918        0                     0       0           1             0   
4919        0                     0       0           0             0   

      acidity  high_fever  abdominal_pain  swelling_of_stomach  \
0           0           0               0                    0   
1           0           0               0                    0   
2           0           0               0                    0   
3           0           0               0                    0   
4           0           0               0                    0   
...       ...         ...             ...                  ...   
4915        0           0               0                    0   
4916        0           0               0                    0   
4917        0           0               0                    0   
4918        0           0               0                    0   
4919        0           1               0                    0   

      redness_of_eyes  runny_nose  chest_pain  \
0                   0           0           0   
1                   0           0           0   
2                   0           0           0   
3                   0           0           0   
4                   0           0           0   
...               ...         ...         ...   
4915                0           0           0   
4916                0           0           0   
4917                0           0           0   
4918                0           0           0   
4919                0           0           0   

                                    prognosis  
0                            Fungal infection  
1                            Fungal infection  
2                            Fungal infection  
3                            Fungal infection  
4                            Fungal infection  
...                                       ...  
4915  (vertigo) Paroymsal  Positional Vertigo  
4916                                     Acne  
4917                  Urinary tract infection  
4918                                Psoriasis  
4919                                 Impetigo  

[4920 rows x 13 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   itching               4920 non-null   int64 
 1   nodal_skin_eruptions  4920 non-null   int64 
 2   chills                4920 non-null   int64 
 3   joint_pain            4920 non-null   int64 
 4   stomach_pain          4920 non-null   int64 
 5   acidity               4920 non-null   int64 
 6   high_fever            4920 non-null   int64 
 7   abdominal_pain        4920 non-null   int64 
 8   swelling_of_stomach   4920 non-null   int64 
 9   redness_of_eyes       4920 non-null   int64 
 10  runny_nose            4920 non-null   int64 
 11  chest_pain            4920 non-null   int64 
 12  prognosis             4920 non-null   object
dtypes: int64(12), object(1)
memory usage: 499.8+ KB


In [14]:
df.prognosis.unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [5]:
from sklearn.preprocessing import LabelEncoder
rf = LabelEncoder()

In [15]:
val = rf.fit_transform(df.prognosis)
val

array([15, 15, 15, ..., 38, 35, 27], shape=(4920,))

In [16]:
df["Diagnosis"] = val

In [17]:
df

itching  nodal_skin_eruptions  chills  joint_pain  stomach_pain  \
0           1                     1       0           0             0   
1           0                     1       0           0             0   
2           1                     1       0           0             0   
3           1                     0       0           0             0   
4           1                     1       0           0             0   
...       ...                   ...     ...         ...           ...   
4915        0                     0       0           0             0   
4916        0                     0       0           0             0   
4917        0                     0       0           0             0   
4918        0                     0       0           1             0   
4919        0                     0       0           0             0   

      acidity  high_fever  abdominal_pain  swelling_of_stomach  \
0           0           0               0                    0   
1           0           0               0                    0   
2           0           0               0                    0   
3           0           0               0                    0   
4           0           0               0                    0   
...       ...         ...             ...                  ...   
4915        0           0               0                    0   
4916        0           0               0                    0   
4917        0           0               0                    0   
4918        0           0               0                    0   
4919        0           1               0                    0   

      redness_of_eyes  runny_nose  chest_pain  \
0                   0           0           0   
1                   0           0           0   
2                   0           0           0   
3                   0           0           0   
4                   0           0           0   
...               ...         ...         ...   
4915                0           0           0   
4916                0           0           0   
4917                0           0           0   
4918                0           0           0   
4919                0           0           0   

                                    prognosis  Diagnosis  
0                            Fungal infection         15  
1                            Fungal infection         15  
2                            Fungal infection         15  
3                            Fungal infection         15  
4                            Fungal infection         15  
...                                       ...        ...  
4915  (vertigo) Paroymsal  Positional Vertigo          0  
4916                                     Acne          2  
4917                  Urinary tract infection         38  
4918                                Psoriasis         35  
4919                                 Impetigo         27  

[4920 rows x 14 columns]

In [18]:
x = df.loc[:,:"chest_pain"]
x

itching  nodal_skin_eruptions  chills  joint_pain  stomach_pain  \
0           1                     1       0           0             0   
1           0                     1       0           0             0   
2           1                     1       0           0             0   
3           1                     0       0           0             0   
4           1                     1       0           0             0   
...       ...                   ...     ...         ...           ...   
4915        0                     0       0           0             0   
4916        0                     0       0           0             0   
4917        0                     0       0           0             0   
4918        0                     0       0           1             0   
4919        0                     0       0           0             0   

      acidity  high_fever  abdominal_pain  swelling_of_stomach  \
0           0           0               0                    0   
1           0           0               0                    0   
2           0           0               0                    0   
3           0           0               0                    0   
4           0           0               0                    0   
...       ...         ...             ...                  ...   
4915        0           0               0                    0   
4916        0           0               0                    0   
4917        0           0               0                    0   
4918        0           0               0                    0   
4919        0           1               0                    0   

      redness_of_eyes  runny_nose  chest_pain  
0                   0           0           0  
1                   0           0           0  
2                   0           0           0  
3                   0           0           0  
4                   0           0           0  
...               ...         ...         ...  
4915                0           0           0  
4916                0           0           0  
4917                0           0           0  
4918                0           0           0  
4919                0           0           0  

[4920 rows x 12 columns]

In [19]:
y = df["Diagnosis"]
y

0       15
1       15
2       15
3       15
4       15
        ..
4915     0
4916     2
4917    38
4918    35
4919    27
Name: Diagnosis, Length: 4920, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

In [22]:
x_train

itching  nodal_skin_eruptions  chills  joint_pain  stomach_pain  \
313         0                     0       0           0             0   
2733        0                     0       1           0             0   
3859        0                     0       0           0             0   
3305        0                     0       1           0             0   
1777        0                     0       0           0             0   
...       ...                   ...     ...         ...           ...   
2522        0                     0       0           0             0   
1884        0                     0       0           0             0   
2048        0                     0       0           0             0   
1468        0                     0       0           1             0   
1620        0                     0       0           1             0   

      acidity  high_fever  abdominal_pain  swelling_of_stomach  \
313         0           0               0                    0   
2733        0           1               0                    0   
3859        0           0               1                    0   
3305        0           1               0                    0   
1777        0           0               0                    0   
...       ...         ...             ...                  ...   
2522        0           0               0                    0   
1884        0           0               0                    1   
2048        0           1               0                    0   
1468        0           1               1                    0   
1620        0           0               0                    0   

      redness_of_eyes  runny_nose  chest_pain  
313                 0           0           0  
2733                0           0           1  
3859                0           0           0  
3305                0           0           1  
1777                0           0           0  
...               ...         ...         ...  
2522                0           0           0  
1884                0           0           0  
2048                0           0           0  
1468                0           0           0  
1620                0           0           0  

[3936 rows x 12 columns]

In [23]:
y_train

313     26
2733    34
3859    33
3305    36
1777    32
        ..
2522    20
1884     3
2048    27
1468    22
1620    35
Name: Diagnosis, Length: 3936, dtype: int64

In [26]:
x_test

itching  nodal_skin_eruptions  chills  joint_pain  stomach_pain  \
1925        0                     0       0           0             0   
1032        0                     0       0           0             0   
1808        1                     0       0           0             0   
1991        0                     0       0           0             0   
4259        0                     0       0           0             0   
...       ...                   ...     ...         ...           ...   
3661        0                     0       0           0             0   
1091        0                     0       1           0             0   
3865        0                     0       0           0             0   
3300        1                     0       0           0             0   
2245        0                     0       0           1             0   

      acidity  high_fever  abdominal_pain  swelling_of_stomach  \
1925        0           0               0                    0   
1032        0           0               0                    0   
1808        0           1               0                    0   
1991        0           0               0                    0   
4259        0           0               0                    0   
...       ...         ...             ...                  ...   
3661        0           0               0                    0   
1091        0           1               0                    0   
3865        1           0               0                    0   
3300        0           0               1                    0   
2245        0           0               1                    0   

      redness_of_eyes  runny_nose  chest_pain  
1925                0           0           0  
1032                0           0           0  
1808                0           0           0  
1991                0           0           0  
4259                0           0           0  
...               ...         ...         ...  
3661                0           0           0  
1091                0           0           1  
3865                0           0           0  
3300                0           0           0  
2245                0           0           0  

[984 rows x 12 columns]

In [25]:
y_test

1925    13
1032    20
1808     8
1991     5
4259     0
        ..
3661     7
1091    34
3865    30
3300    19
2245    40
Name: Diagnosis, Length: 984, dtype: int64

In [28]:
from sklearn.ensemble import RandomForestClassifier
dt = RandomForestClassifier(n_estimators=100,criterion="entropy")
dt.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy')

In [31]:
y_pred = dt.predict(x_test)
y_pred

array([25, 25,  8, 25, 25, 25, 30, 30,  3, 14, 25, 25, 22,  4, 25, 25, 19,
        8,  8, 21, 25, 25, 25, 35,  1,  4, 11, 29, 19, 28, 25, 37,  1, 25,
       25,  1, 21, 18, 14, 10, 35, 34, 15, 11, 18, 11, 19, 28, 25, 33, 25,
       29, 19, 11, 25, 25, 25, 34, 35, 22,  1, 25, 25, 35, 25, 35, 25,  1,
        1,  1, 18, 25, 34,  4, 25, 25,  8, 25, 21, 25,  1,  1,  1, 25, 35,
        3, 21, 18, 34,  3,  1, 35, 16,  1, 25, 14, 34,  3, 34, 29, 34, 34,
       25, 25, 25, 25, 25, 22, 25, 25, 35,  8, 28, 37, 28, 25, 21, 25, 15,
       34, 25, 28, 25, 29, 25, 14, 11, 25, 25,  3, 11, 25, 28, 25, 25, 11,
       25, 25, 30,  3, 15, 15, 21, 33, 25, 10,  3, 16, 25, 33, 25,  1, 11,
       18, 18, 16,  1,  1, 25, 25, 16, 21, 25, 29, 30,  1, 25,  4, 16, 22,
       21, 10, 25,  1, 30, 25,  1, 11, 29, 35, 28, 30, 25, 10, 25, 25, 25,
       21, 34,  1, 21, 33,  1, 25, 37, 25, 35, 25, 30, 19, 22, 19, 25, 18,
       25, 25, 25, 15, 29, 15, 37, 18, 25, 25, 21,  3, 28,  1, 34, 19, 35,
        1, 34, 21,  1, 18

In [33]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [34]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.46646341463414637
[[ 0  0  0 ...  0  0  0]
 [ 0 20  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        31
           1       0.29      0.95      0.44        21
           2       0.00      0.00      0.00        25
           3       1.00      0.95      0.98        22
           4       0.95      0.95      0.95        19
           5       0.00      0.00      0.00        22
           6       0.00      0.00      0.00        24
           7       0.00      0.00      0.00        30
           8       1.00      0.94      0.97        31
           9       0.00      0.00      0.00        27
          10       1.00      1.00      1.00        22
          11       1.00      0.96      0.98        25
          12       0.00      0.00      0.00        22
          13       0.00      0.00      0.00        20
          14 

C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is",

In [35]:
import pickle